StellarStatBot: stat Namespace Reference
stat Namespace Reference
Functions
doc_import (doc_name)
columns_print (doc_name)
description_print (doc_name)
info_print (doc_name)
mean_count (doc_name, column_name)
median_count (doc_name, column_name)
mode_count (doc_name, column_name)
trim_mean_10_count (doc_name, column_name)
range_count (doc_name, column_name)
iqrange_count (doc_name, column_name)
var_count (doc_name, column_name)
std_dev_count (doc_name, column_name)
mad_count (doc_name, column_name)
unique_count (doc_name, column_name)
unique (doc_name, column_name)
value_counts_count (doc_name, column_name)
pie_chart (doc_name, column_name)
count_plot (doc_name, column_name)
dis_plot_num (doc_name, column_name)
box_plot (doc_name, column_name)
strip_plot (doc_name, column_name)
swarm_plot (doc_name, column_name)
violin_plot (doc_name, column_name)
Detailed Description
The file stat.py contains functions for analyzing statistical data from CSV files.
It allows importing data from a CSV file into a DataFrame object, displaying column information,
generating descriptive summaries, and computing various statistical metrics such as mean, median,
mode, range, etc. Additionally, the file implements functions for creating various types of plots,
such as histograms, box plots, and others, for data visualization purposes.
Function Documentation
box_plot()
stat.box_plot (doc_name, column_name)
The purpose of this function is to generate a box plot for numerical data.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 - column_name (str): The name of the numerical column for which the box plot is generated.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The box plot is created using Seaborn.
 - The title of the box plot reflects the column name.
Return Value:
 - The function returns the box plot as a base64-encoded image.
References doc_import().
columns_print()
stat.columns_print (doc_name)
This function serves the purpose of printing the columns of a DataFrame along with their respective data types.
The purpose of this function is to create a dictionary that maps column names to their corresponding data types.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
Behavior:
 - Imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The function iterates through the columns of the DataFrame (df).
 - For each column, it appends the column name to the column_list.
 - The columns_type_dict is created by mapping column names to their respective data types using dict(df.dtypes)
Return Value:
 - The function returns the dictionary containing column names as keys and data types as values.
References doc_import().
count_plot()
stat.count_plot (doc_name, column_name)
This function generates a count plot to visualize the distribution of categorical data within a
specified column in a DataFrame.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 - column_name (str): The name of the categorical column for which the count plot is generated.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - If there are more than 8 unique values in the specified column, smaller categories are grouped as “Others.”
 - The count plot is created using Seaborn and Matplotlib.
 - The title of the count plot reflects the column name.
 - For each bar in the count plot, the actual count is displayed as an annotation.
Return Value:
 - The function returns the count plot as a base64-encoded image.
References doc_import(), and unique().
description_print()
stat.description_print (doc_name)
This function generates a descriptive summary of a DataFrame created from a CSV file.
The purpose of this function is to create a descriptive summary table for the given DataFrame.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The describe_df DataFrame is created by rounding the descriptive statistics of the original DataFrame (df) to two decimal places.
 - The “Statistics” column is inserted at the beginning of the describe_df DataFrame.
 - A table is generated using Matplotlib and added to the figure (fig) with appropriate formatting.
 - The table is auto-sized to fit the column widths.
 - The table is saved as a PNG image in the buffer.
Return Value:
 - The image in the buffer is base64-encoded and returned as a string.
References doc_import().
dis_plot_num()
stat.dis_plot_num (doc_name, column_name)
The purpose of this function is to generate a histogram for numerical data.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 - column_name (str): The name of the numerical column for which the histogram is generated.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The histogram is created using Seaborn’s displot function with specified parameters.
 - The title of the histogram reflects the column name.
Return Value:
 - The function returns the histogram as a base64-encoded image.
References doc_import().
doc_import()
stat.doc_import (doc_name)
This function serves the purpose of importing a CSV file into a Pandas DataFrame.
Parameters:
 - doc_name (str): The name of the CSV file to be imported.
Return Value:
 - The function returns a Pandas DataFrame containing the data from the specified CSV file.
Referenced by box_plot(), columns_print(), count_plot(), description_print(), dis_plot_num(), info_print(), iqrange_count(), mad_count(), mean_count(), median_count(), mode_count(), pie_chart(), range_count(), std_dev_count(), strip_plot(), swarm_plot(), trim_mean_10_count(), unique(), unique_count(), value_counts_count(), var_count(), and violin_plot().
info_print()
stat.info_print (doc_name)
This function serves the purpose of providing detailed information about a DataFrame created from a CSV file.
The purpose of this function is to generate a summary of the DataFrame’s structure and data types.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The standard output (usually printed to the console) is redirected to a buffer using redirect_stdout.
 - The df.info() method is called within this context, capturing the information in the buffer.
Return Value:
 - The function returns the DataFrame information as a string.
References doc_import().
iqrange_count()
stat.iqrange_count (doc_name, column_name)
The purpose of this function is to calculate the interquartile range (IQR) of a specific column within the DataFrame.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 - column_name (str): The name of the column for which the mean is calculated.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The IQR value of the specified column (column_name) is computed using iqr(df[column_name]).
Return Value:
 - The function returns the IQR value as a floating-point number.
References doc_import().
mad_count()
stat.mad_count (doc_name, column_name)
The purpose of this function is to calculate the mean absolute deviation of a specific column within the DataFrame.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 - column_name (str): The name of the column for which the mean is calculated.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The mean absolute deviation (MAD) value of the specified column (column_name) is computed
    using median_abs_deviation(df[column_name]).
Return Value:
 - The function returns the mean absolute deviation value as a floating-point number.
References doc_import().
mean_count()
stat.mean_count (doc_name, column_name)
This function calculates the mean value of a specified column in a DataFrame created from a CSV file.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 - column_name (str): The name of the column for which the mean is calculated.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The mean value of the specified column (column_name) is computed using df[column_name].mean().
Return Value:
 - The function returns the mean value as a floating-point number.
References doc_import().
median_count()
stat.median_count (doc_name, column_name)
This function computes the median value of a specified column in a DataFrame created from a CSV file.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 - column_name (str): The name of the column for which the mean is calculated.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The median value of the specified column (column_name) is computed using df[column_name].median().
Return Value:
 - The function returns the median value as a floating-point number.
References doc_import().
mode_count()
stat.mode_count (doc_name, column_name)
This function computes the mode (most frequent value) of a specified column in a DataFrame created from a CSV file.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 - column_name (str): The name of the column for which the mean is calculated.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The mode value of the specified column (column_name) is extracted using df[column_name].mode().
Return Value:
 - The function returns the mode value as a string.
References doc_import().
pie_chart()
stat.pie_chart (doc_name, column_name)
This function generates a pie chart to visualize the proportions of different categories within a
specified categorical column in a DataFrame.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 - column_name (str): The name of the categorical column for which the pie chart is generated.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - If there are more than 8 unique values in the specified column, smaller categories are grouped as “Others.”
 - The pie chart is created using Seaborn and Matplotlib.
 - The title of the pie chart reflects the column name.
Return Value:
 - The function returns the pie chart as a base64-encoded image.
References doc_import(), and unique().
range_count()
stat.range_count (doc_name, column_name)
This function computes the range (difference between the maximum and minimum values) of a specified column in a DataFrame created from a CSV file.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 - column_name (str): The name of the column for which the mean is calculated.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The range value of the specified column (column_name) is computed as the difference between the maximum
    and minimum values using df[column_name].max() - df[column_name].min().
Return Value:
 - The function returns the range value as a floating-point number.
References doc_import().
std_dev_count()
stat.std_dev_count (doc_name, column_name)
The purpose of this function is to calculate the standard deviation of a specific column within the DataFrame.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 - column_name (str): The name of the column for which the mean is calculated.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The standard deviation value of the specified column (column_name) is computed using df[column_name].std().
Return Value:
 - The function returns the standard deviation value as a floating-point number.
References doc_import().
strip_plot()
stat.strip_plot (doc_name, column_name)
The purpose of this function is to generate a strip plot for numerical data.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 - column_name (str): The name of the numerical column for which the strip plot is generated.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The strip plot is created using Seaborn’s stripplot function with specified parameters.
 - The title of the strip plot reflects the column name.
Return Value:
 - The function returns the strip plot as a base64-encoded image.
References doc_import().
swarm_plot()
stat.swarm_plot (doc_name, column_name)
The purpose of this function is to generate a swarm plot for numerical data.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 - column_name (str): The name of the numerical column for which the swarm plot is generated.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The swarm plot is created using Seaborn.
 - The title of the swarm plot reflects the column name.
Return Value:
 - The function returns the swarm plot as a base64-encoded image.
 Warning!!!:
 - Generating this plot can be computationally intensive for large datasets (greater than 5000 data points). Please use caution.
References doc_import().
trim_mean_10_count()
stat.trim_mean_10_count (doc_name, column_name)
This function computes the trimmed mean (10%) value of a specified column in a DataFrame created from a CSV file.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 - column_name (str): The name of the column for which the mean is calculated.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The trimmed mean (10%) value of the specified column (column_name) is computed using trim_mean(df[column_name],
    proportiontocut=0.1).
Return Value:
 - The function returns the trimmed mean (10%) value as a floating-point number.
References doc_import().
unique()
stat.unique (doc_name, column_name)
The purpose of this function is to retrieve the unique values in a specific column within the DataFrame.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 - column_name (str): The name of the column for which the unique values are retrieved.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The unique values in the specified column (column_name) are obtained using df[column_name].unique().
Return Value:
 - The function returns a list of unique values.
References doc_import(), and unique().
Referenced by count_plot(), pie_chart(), unique(), and unique_count().
unique_count()
stat.unique_count (doc_name, column_name)
The purpose of this function is to calculate the count of unique values in a specific column within the DataFrame.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 - column_name (str): The name of the column for which the mean is calculated.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The count of unique values in the specified column (column_name) is determined using len(df[column_name].unique()).
Return Value:
 - The function returns the count of unique values as an integer.
References doc_import(), and unique().
value_counts_count()
stat.value_counts_count (doc_name, column_name)
The purpose of this function is to calculate the normalized value counts of unique values in a specific column within the DataFrame.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 - column_name (str): The name of the column for which the normalized value counts are calculated.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The normalized value counts of unique values in the specified column (column_name) are computed
    using df[column_name].value_counts(normalize=True).
Return Value:
 - The function returns a Pandas Series containing the normalized value counts.
References doc_import().
var_count()
stat.var_count (doc_name, column_name)
The purpose of this function is to calculate the variance of a specific column within the DataFrame.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 - column_name (str): The name of the column for which the mean is calculated.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
Return Value:
 - The function returns the variance value as a floating-point number.
References doc_import().
violin_plot()
stat.violin_plot (doc_name, column_name)
This function generates a violin plot to visualize the distribution of numerical data within a specified column in a DataFrame.
Parameters:
 - doc_name (str): The name of the CSV file from which the DataFrame is created.
 - column_name (str): The name of the numerical column for which the violin plot is generated.
Behavior:
 - The function imports the CSV file using the doc_import(doc_name) function to create a DataFrame (df).
 - The violin plot is created using Seaborn.
 - The title of the violin plot reflects the column name.
 - The inner_kws parameter is used to customize the appearance of the violin plot.
Return Value:
 - The function returns the violin plot as a base64-encoded image.
References doc_import().